import { expect, test } from '@playwright/test'

test('cadastro fica pendente e pode ser ativado manualmente', async ({ page }) => {
  await page.goto('/ingresso')
  await expect(page.getByRole('link', { name: 'Comprar pelo WhatsApp' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'VOCÊ JÁ TEM UMA CONTA?' })).toBeVisible()
  await page.getByRole('button', { name: 'Não, criar conta' }).click()
  await page.getByLabel('Nome completo').fill('Maria Teste')
  await page.getByLabel('WhatsApp').fill('37999999999')
  await page.getByLabel('E-mail').fill('maria@example.com')
  await page.getByLabel('Senha', { exact: true }).fill('senha-segura-123')
  await page.getByLabel('Confirmar senha').fill('senha-segura-123')
  await page.getByRole('button', { name: 'Criar minha conta' }).click()
  await expect(page.getByRole('heading', { name: 'FALTA 1 PASSO' })).toBeVisible()
  await expect(page.getByText('Conta criada')).toBeVisible()
  await expect(page.getByText('Aguarde a ativação')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Comprar pelo WhatsApp' })).toBeVisible()
  await expect(page.locator('.site-header')).toHaveCount(0)

  await page.goto('/admin/login')
  await page.getByLabel('E-mail').fill('eduardosoares.email@gmail.com')
  await page.getByLabel('Senha', { exact: true }).fill('bXEz9Pa')
  await page.getByRole('button', { name: 'Entrar' }).click()
  await expect(page).toHaveURL(/\/admin$/)
  await page.goto('/admin/convites')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Ativar ingresso' }).click()

  await page.goto('/ingresso')
  await expect(page.getByRole('heading', { name: 'INGRESSO ATIVO' })).toBeVisible()
  await expect(page.getByAltText(/QR Code do convite/)).toBeVisible()
  await expect(page.getByText('Precisa de ajuda?')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Falar pelo WhatsApp' })).toBeVisible()
  await expect(page.locator('.site-header')).toHaveCount(0)

  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Comprar ingresso', exact: true })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Meu ingresso', exact: true }).nth(1)).toBeVisible()
  await page.getByRole('link', { name: 'Meu ingresso', exact: true }).nth(1).click()
  await expect(page.getByRole('heading', { name: 'INGRESSO ATIVO' })).toBeVisible()
})

test('menu do evento mantém as ações funcionando sem hash', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByLabel('24 de outubro de 2026')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Tirar dúvidas pelo WhatsApp' })).toHaveAttribute('href', /wa\.me\/553798702778/)
  const menu = page.getByRole('button', { name: 'Abrir menu' })
  if (await menu.isVisible()) await menu.click()
  await page.getByRole('button', { name: 'O evento', exact: true }).click()
  await expect(page).not.toHaveURL(/#evento/)
  await page.getByRole('link', { name: 'Comprar ingresso' }).nth(1).click()
  await expect(page).toHaveURL(/\/ingresso/)
})
